//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Hospitalario.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cama()
        {
            this.internacion = new HashSet<internacion>();
        }
    
        public int id_cama { get; set; }
        public int nro_habitacion { get; set; }
        public int id_estado_cama { get; set; }
    
        public virtual estado_cama estado_cama { get; set; }
        public virtual habitacion habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<internacion> internacion { get; set; }
    }
}
