//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Hospitalario.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public int id_paciente { get; set; }
        public int dni { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string observaciones { get; set; }
        public string direccion { get; set; }
        public string estado { get; set; }
        public string obra_social { get; set; }
        public string telefono { get; set; }
        public Nullable<int> nro_afiliado { get; set; }
    }
}
