//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Hospitalario.CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sistema_HospitalarioEntities_Conexion : DbContext
    {
        public Sistema_HospitalarioEntities_Conexion()
            : base("name=Sistema_HospitalarioEntities_Conexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cama> cama { get; set; }
        public virtual DbSet<especialidad> especialidad { get; set; }
        public virtual DbSet<estado_cama> estado_cama { get; set; }
        public virtual DbSet<estado_paciente> estado_paciente { get; set; }
        public virtual DbSet<estado_turno> estado_turno { get; set; }
        public virtual DbSet<estado_usuario> estado_usuario { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<internacion> internacion { get; set; }
        public virtual DbSet<medico> medico { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<procedimiento> procedimiento { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<subespecialidad> subespecialidad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<tipo_habitacion> tipo_habitacion { get; set; }
        public virtual DbSet<turno> turno { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
