//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Hospitalario.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno
    {
        public int id_turno { get; set; }
        public System.DateTime fecha_turno { get; set; }
        public System.DateTime fecha_registracion { get; set; }
        public int id_procedimiento { get; set; }
        public int id_paciente { get; set; }
        public int id_medico { get; set; }
        public int id_estado_turno { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public string motivo { get; set; }
    
        public virtual estado_turno estado_turno { get; set; }
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual procedimiento procedimiento { get; set; }
    }
}
